"use client";

import { ArrowUpRight, BriefcaseBusiness, CheckCircle2, Clock3, MapPin, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";

type WorkMode = "Remote" | "Onsite" | "Hybrid";
interface Job { id: number; title: string; department: string; mode: WorkMode; location: string; schedule: string; description: string; requirements: string[]; }

const jobs: Job[] = [
  { id: 1, title: "Online Quran Teacher", department: "Teaching", mode: "Remote", location: "Worldwide", schedule: "Flexible · Part-time", description: "Guide children and adults through Quran reading, Tajweed, and consistent one-to-one online lessons.", requirements: ["Strong Quran recitation and Tajweed", "Online teaching confidence", "Patient student communication"] },
  { id: 2, title: "Female Quran & Islamic Studies Teacher", department: "Teaching", mode: "Remote", location: "Worldwide", schedule: "Flexible · Full/Part-time", description: "Deliver supportive Quran and Islamic Studies lessons for women, children, and family learners.", requirements: ["Relevant Islamic qualification", "Clear English or Urdu communication", "Experience teaching online"] },
  { id: 3, title: "Student Enrollment Advisor", department: "Admissions", mode: "Onsite", location: "Islamabad, Pakistan", schedule: "Full-time", description: "Help families choose courses, arrange trial classes, and begin their learning journey with confidence.", requirements: ["Strong communication skills", "Organized follow-up", "Customer support experience"] },
  { id: 4, title: "Academic Coordinator", department: "Academic Operations", mode: "Hybrid", location: "Islamabad, Pakistan", schedule: "Full-time", description: "Coordinate teachers, student schedules, progress records, and a consistently high-quality learning experience.", requirements: ["Education coordination experience", "Excellent organization", "Confident team communication"] },
  { id: 5, title: "Islamic Content Writer", department: "Content", mode: "Remote", location: "Worldwide", schedule: "Contract", description: "Create clear, thoughtful articles and learning resources for Quran students, parents, and Muslim families.", requirements: ["Strong English writing", "Reliable Islamic research", "Ability to simplify complex ideas"] },
  { id: 6, title: "Social Media & Video Coordinator", department: "Marketing", mode: "Hybrid", location: "Islamabad, Pakistan", schedule: "Full-time", description: "Plan and publish short educational videos, teacher sessions, reminders, and institute updates across social platforms.", requirements: ["Short-form content experience", "Basic video editing", "Strong editorial judgment"] },
];

function ApplyModal({ job, onClose }: { job: Job; onClose: () => void }) {
  const [sent, setSent] = useState(false);
  useEffect(() => { document.body.style.overflow = "hidden"; const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", close); return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", close); }; }, [onClose]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  return <div className="fixed inset-0 z-[9999] flex items-center justify-center overflow-y-auto bg-[#071F1B]/80 p-4 backdrop-blur-lg" role="dialog" aria-modal="true" aria-label={`Apply for ${job.title}`} onClick={onClose}><div className="relative my-6 w-full max-w-xl rounded-[16px] bg-[#FBF6EF] p-6 shadow-2xl sm:p-9" onClick={(event) => event.stopPropagation()}><button type="button" onClick={onClose} aria-label="Close application" className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-white text-[#0D463E]"><X className="size-5" /></button><p className="font-body text-xs font-bold uppercase tracking-[0.15em] text-[#0D706D]">Application</p><h2 className="mt-3 pr-12 font-heading text-3xl font-medium text-[#0D463E]">{job.title}</h2><p className="mt-3 font-body text-sm text-[#0D463E]/60">{job.mode} · {job.location}</p>{sent ? <div className="mt-8 rounded-[12px] bg-[#0D463E] p-8 text-center text-white"><CheckCircle2 className="mx-auto size-10 text-[#D0A86C]" /><h3 className="mt-4 font-heading text-2xl">Application received</h3><p className="mt-2 font-body text-sm leading-6 text-white/65">Thank you for your interest. Our team will review your details and contact shortlisted candidates.</p></div> : <form onSubmit={submit} className="mt-8 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="font-body text-sm font-semibold text-[#0D463E]">Full name<input required className="mt-2 h-12 w-full rounded-[6px] border border-[#0D463E]/15 bg-white px-4 font-normal outline-none focus:border-[#0D706D]" /></label><label className="font-body text-sm font-semibold text-[#0D463E]">Email address<input required type="email" className="mt-2 h-12 w-full rounded-[6px] border border-[#0D463E]/15 bg-white px-4 font-normal outline-none focus:border-[#0D706D]" /></label></div><label className="block font-body text-sm font-semibold text-[#0D463E]">Phone / WhatsApp<input required className="mt-2 h-12 w-full rounded-[6px] border border-[#0D463E]/15 bg-white px-4 font-normal outline-none focus:border-[#0D706D]" /></label><label className="block font-body text-sm font-semibold text-[#0D463E]">Experience and qualifications<textarea required rows={4} placeholder="Tell us briefly about your relevant experience..." className="mt-2 w-full resize-y rounded-[6px] border border-[#0D463E]/15 bg-white px-4 py-3 font-normal leading-6 outline-none focus:border-[#0D706D]" /></label><label className="block font-body text-sm font-semibold text-[#0D463E]">CV / résumé<input required type="file" accept=".pdf,.doc,.docx" className="mt-2 block w-full rounded-[6px] border border-[#0D463E]/15 bg-white p-3 font-normal file:mr-3 file:rounded file:border-0 file:bg-[#0D463E]/8 file:px-3 file:py-2 file:text-[#0D463E]" /></label><button type="submit" className="h-12 w-full rounded-[6px] bg-[#0D463E] font-body text-sm font-bold text-white hover:bg-[#146154]">Submit Application</button></form>}</div></div>;
}

export default function JobsBoard() {
  const [filter, setFilter] = useState<"All" | WorkMode>("All"); const [active, setActive] = useState<Job | null>(null);
  const visible = useMemo(() => jobs.filter((job) => filter === "All" || job.mode === filter), [filter]);
  return <section id="open-positions" className="w-full bg-white py-24 sm:py-28 min-[1024px]:py-32"><div className="container"><div className="mx-auto max-w-4xl text-center"><p className="font-body text-xs font-bold uppercase tracking-[0.18em] text-[#0D706D]">Open Positions</p><h2 className="mt-4 font-heading text-4xl font-medium text-[#0D463E] sm:text-5xl min-[1024px]:text-[58px]">Find Your Place at <span className="font-accent font-normal italic">Haramain</span></h2><p className="mx-auto mt-5 max-w-3xl font-body text-base leading-7 text-[#0D463E]/62">Explore meaningful opportunities in teaching, admissions, academic operations, content, and digital media.</p><div className="mt-8 inline-flex flex-wrap justify-center rounded-full bg-[#FBF6EF] p-1.5">{(["All", "Remote", "Onsite", "Hybrid"] as const).map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-full px-5 py-2.5 font-body text-sm font-bold transition-colors ${filter === item ? "bg-[#0D463E] text-white" : "text-[#0D463E] hover:bg-white"}`}>{item}</button>)}</div></div><div className="mx-auto mt-14 max-w-6xl overflow-hidden rounded-[16px] border border-[#0D463E]/10 bg-[#FBF6EF]">{visible.map((job) => <article key={job.id} className="group grid gap-6 border-b border-[#0D463E]/10 p-6 last:border-b-0 sm:p-8 min-[900px]:grid-cols-[1fr_auto] min-[900px]:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#0D463E] px-3 py-1 font-body text-[10px] font-bold uppercase tracking-wider text-white">{job.mode}</span><span className="font-body text-xs font-semibold text-[#0D706D]">{job.department}</span></div><h3 className="mt-4 font-heading text-2xl font-medium text-[#0D463E] sm:text-3xl">{job.title}</h3><p className="mt-3 max-w-3xl font-body text-sm leading-6 text-[#0D463E]/62">{job.description}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 font-body text-xs text-[#0D463E]/50"><span className="inline-flex items-center gap-1.5"><MapPin className="size-3.5" />{job.location}</span><span className="inline-flex items-center gap-1.5"><Clock3 className="size-3.5" />{job.schedule}</span><span className="inline-flex items-center gap-1.5"><BriefcaseBusiness className="size-3.5" />{job.requirements.length} key requirements</span></div></div><button type="button" onClick={() => setActive(job)} className="inline-flex h-12 items-center justify-center gap-2 rounded-[6px] bg-[#0D463E] px-6 font-body text-sm font-bold text-white transition-colors hover:bg-[#146154]">Apply Now <ArrowUpRight className="size-4" /></button></article>)}{visible.length === 0 && <div className="py-16 text-center font-body text-[#0D463E]/55">No roles are currently available for this work type.</div>}</div></div>{active && <ApplyModal job={active} onClose={() => setActive(null)} />}</section>;
}
