"use client";

import Image, { type StaticImageData } from "next/image";
import { ArrowUpRight, BookOpenText, CalendarDays, CheckCircle2, Clock3, Quote, SlidersHorizontal, UserRound, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import imageOne from "@/assets/gallery-1.jpg";
import imageTwo from "@/assets/gallery-2.jpg";
import imageThree from "@/assets/gallery-3.jpg";
import imageFour from "@/assets/gallery-4.jpg";
import imageFive from "@/assets/gallery-5.jpg";
import imageSix from "@/assets/gallery-6.jpg";
import imageSeven from "@/assets/gallery-7.jpg";
import imageEight from "@/assets/gallery-8.jpg";
import imageNine from "@/assets/gallery-9.jpg";
import imageTen from "@/assets/gallery-10.jpg";

type Category = "Quran Learning" | "Tajweed" | "Hifz & Memorization" | "Islamic Studies" | "Kids & Parenting" | "Duas & Guidance" | "Muslim Lifestyle";
type SortOption = "Latest" | "Popular" | "Featured";

interface BlogSection { heading: string; body: string; }
interface BlogPost { id: number; title: string; excerpt: string; category: Category; author: string; date: string; readTime: string; image: StaticImageData; popularity: number; featured: boolean; introduction: string; sections: BlogSection[]; takeaway: string; }

const categories = ["All Blogs", "Quran Learning", "Tajweed", "Hifz & Memorization", "Islamic Studies", "Kids & Parenting", "Duas & Guidance", "Muslim Lifestyle"] as const;
const authors = ["All Authors", "Qari Nouman", "Qari Abdul Rahman", "Qari Rizwan", "Ustadha Maryam", "Mufti Hamza"];

const posts: BlogPost[] = [
  { id: 10, title: "How to Build a Lifelong Connection with the Quran", excerpt: "A practical roadmap for making Quran reading, reflection, and application part of everyday life.", category: "Quran Learning", author: "Qari Nouman", date: "August 28, 2026", readTime: "7 min read", image: imageOne, popularity: 100, featured: true, introduction: "A lasting relationship with the Quran is not built through occasional bursts of effort. It grows through sincere intention, manageable routines, thoughtful reflection, and the willingness to return every day.", sections: [{ heading: "Begin with a clear intention", body: "Remind yourself that Quran learning is an act of worship and guidance. A sincere purpose makes even a few carefully read verses meaningful and helps consistency feel valuable rather than burdensome." }, { heading: "Choose a routine you can protect", body: "Select a quiet time and a realistic amount to read. Ten focused minutes after Fajr or before sleep can build a stronger habit than an ambitious schedule that is difficult to maintain." }, { heading: "Move from reading to living", body: "Pause over meanings, note one lesson, and ask how it can shape your speech, patience, family life, or worship. The Quran becomes a companion when its guidance enters daily choices." }], takeaway: "Start small, remain sincere, and protect your daily meeting with the Quran." },
  { id: 9, title: "Quran Reading for Beginners: A Clear Starting Path", excerpt: "Learn how letters, sounds, joining, and guided practice come together for confident Quran reading.", category: "Quran Learning", author: "Qari Abdul Rahman", date: "August 20, 2026", readTime: "6 min read", image: imageTwo, popularity: 91, featured: false, introduction: "Beginning Quran reading can feel unfamiliar, but a structured path makes every stage understandable. The goal is steady accuracy, not hurried progress.", sections: [{ heading: "Master the Arabic letters", body: "Learn each letter in its different written forms and listen closely to its correct sound. Strong recognition reduces hesitation later." }, { heading: "Practise joining and vowels", body: "Short vowels, sukoon, shaddah, and joined letters turn recognition into fluent reading. Repeat short examples until they become comfortable." }, { heading: "Read with a teacher", body: "A teacher hears errors that a learner may not notice and demonstrates pronunciation clearly. Regular correction prevents small mistakes from becoming habits." }], takeaway: "A patient foundation creates confident, accurate Quran reading." },
  { id: 8, title: "Five Tajweed Habits That Improve Recitation", excerpt: "Simple practices that help learners protect pronunciation, rhythm, and clarity while reciting.", category: "Tajweed", author: "Qari Rizwan", date: "August 12, 2026", readTime: "5 min read", image: imageThree, popularity: 96, featured: true, introduction: "Tajweed improves through attentive listening and repeated practice. A few focused habits can make recitation clearer and more controlled.", sections: [{ heading: "Slow down", body: "A measured pace gives every letter its right and allows the tongue to reach each articulation point without rushing." }, { heading: "Listen and imitate", body: "Choose a reliable reciter, listen to a short passage, and repeat it carefully. Comparison trains the ear as well as the voice." }, { heading: "Record your recitation", body: "Listening back reveals swallowed vowels, uneven pauses, and unclear letters. Note one issue at a time and practise it with your teacher." }], takeaway: "Clear recitation grows from mindful repetition, listening, and correction." },
  { id: 7, title: "A Sustainable Hifz Routine for Busy Students", excerpt: "Balance new memorization, revision, school, and family life with a realistic weekly system.", category: "Hifz & Memorization", author: "Qari Nouman", date: "August 3, 2026", readTime: "8 min read", image: imageFour, popularity: 94, featured: true, introduction: "Successful memorization depends less on speed and more on consistent revision. A sustainable routine protects both new lessons and what has already been memorized.", sections: [{ heading: "Divide the work", body: "Keep separate time for new memorization, recent revision, and older revision. Each part has a different purpose and should not replace the others." }, { heading: "Use your strongest time", body: "Many learners memorize best when the mind is fresh. Identify that period and reserve it for new verses while using lighter moments for review." }, { heading: "Recite to someone", body: "Daily listening by a teacher or family member creates accountability and catches mistakes before they settle into memory." }], takeaway: "Protect revision, keep new portions realistic, and measure progress over months—not days." },
  { id: 6, title: "Essential Islamic Studies Every Muslim Should Learn", excerpt: "A balanced introduction to beliefs, worship, character, Seerah, and practical everyday guidance.", category: "Islamic Studies", author: "Mufti Hamza", date: "July 24, 2026", readTime: "7 min read", image: imageFive, popularity: 89, featured: false, introduction: "Essential Islamic knowledge gives worship clarity and daily life direction. Learning should connect sound understanding with sincere action and good character.", sections: [{ heading: "Know the foundations of faith", body: "Clear understanding of core beliefs gives meaning to worship and helps Muslims approach questions with confidence and humility." }, { heading: "Learn worship correctly", body: "Study purification, Salah, fasting, charity, and daily duas with reliable guidance so regular worship is performed consciously." }, { heading: "Develop Islamic character", body: "Truthfulness, patience, mercy, responsibility, and respect are not secondary topics. They are visible expressions of faith." }], takeaway: "Beneficial knowledge should improve both worship and the way we treat people." },
  { id: 5, title: "Helping Children Love Quran Learning", excerpt: "Encouraging strategies for parents who want Quran study to feel warm, meaningful, and consistent.", category: "Kids & Parenting", author: "Ustadha Maryam", date: "July 15, 2026", readTime: "6 min read", image: imageSix, popularity: 98, featured: true, introduction: "Children connect with Quran learning when they feel safe, encouraged, and understood. A loving environment makes consistency easier and progress more meaningful.", sections: [{ heading: "Celebrate effort", body: "Praise careful listening, good manners, and persistence—not only perfect results. This teaches children that learning is a journey." }, { heading: "Keep goals age-appropriate", body: "Short, focused lessons often work better than long sessions. Match expectations to the child's age, energy, and current ability." }, { heading: "Model the relationship", body: "Let children see adults reading, listening to, and speaking warmly about the Quran. Example gives lessons emotional meaning." }], takeaway: "Gentle consistency and sincere encouragement help children grow into willing learners." },
  { id: 4, title: "Daily Duas That Bring Mindfulness to Your Routine", excerpt: "Understand how simple prophetic supplications connect ordinary moments with remembrance and gratitude.", category: "Duas & Guidance", author: "Qari Abdul Rahman", date: "July 6, 2026", readTime: "5 min read", image: imageSeven, popularity: 87, featured: false, introduction: "Daily duas transform familiar routines into moments of remembrance. Their benefit grows when we learn their meanings and recite them attentively.", sections: [{ heading: "Learn in small groups", body: "Begin with duas connected to waking, eating, leaving home, and sleeping. A few practised consistently are better than many forgotten." }, { heading: "Understand the meaning", body: "Knowing what you ask from Allah brings presence to the words and makes each supplication easier to remember." }, { heading: "Create gentle reminders", body: "Place a small card near a regular activity or practise together as a family until the dua becomes naturally connected to the moment." }], takeaway: "Let everyday actions become invitations to remember Allah." },
  { id: 3, title: "Arabic Language Skills That Support Quran Study", excerpt: "See how vocabulary, grammar, and repeated Quranic expressions deepen understanding over time.", category: "Quran Learning", author: "Qari Rizwan", date: "June 25, 2026", readTime: "7 min read", image: imageEight, popularity: 85, featured: false, introduction: "Arabic study opens another layer of connection with the Quran. Learners do not need fluency before benefiting from common words and patterns.", sections: [{ heading: "Start with recurring vocabulary", body: "Many important words appear repeatedly throughout the Quran. Learning them first brings quick recognition and motivation." }, { heading: "Notice word patterns", body: "Basic roots and common forms help learners see relationships between words and understand how meanings develop." }, { heading: "Connect language to recitation", body: "Use verses already familiar from Salah. Studying their words and structure turns memorized recitation into conscious understanding." }], takeaway: "A little Arabic learned consistently can transform familiar verses." },
  { id: 2, title: "Making Islamic Learning Part of Family Life", excerpt: "Practical ways to create a home environment shaped by knowledge, worship, kindness, and reflection.", category: "Muslim Lifestyle", author: "Ustadha Maryam", date: "June 14, 2026", readTime: "6 min read", image: imageNine, popularity: 92, featured: true, introduction: "A learning home is not created by constant formal lessons. It grows through shared worship, warm conversations, visible values, and simple routines.", sections: [{ heading: "Choose one family learning moment", body: "Read a short story, verse translation, or hadith together once a week. Keep the atmosphere welcoming and allow everyone to ask questions." }, { heading: "Connect values to real situations", body: "When discussing honesty, gratitude, or patience, point to moments from school, work, and family life where the value can be practised." }, { heading: "Make worship visible and shared", body: "Pray together when possible, exchange reminders kindly, and celebrate progress without turning worship into competition." }], takeaway: "Small shared practices can give faith a natural place in family life." },
  { id: 1, title: "Staying Motivated Through Every Stage of Learning", excerpt: "How to respond to slow progress, renew intention, and keep moving with patience and hope.", category: "Muslim Lifestyle", author: "Mufti Hamza", date: "June 1, 2026", readTime: "5 min read", image: imageTen, popularity: 90, featured: false, introduction: "Every learner experiences days of energy and days of difficulty. Lasting progress comes from returning with patience rather than waiting for perfect motivation.", sections: [{ heading: "Reconnect with your purpose", body: "Remember why you began and ask Allah for beneficial knowledge. Purpose gives value to practice even when improvement feels slow." }, { heading: "Measure consistency", body: "Count the days you showed up, the mistakes you corrected, and the habits you protected—not only pages completed." }, { heading: "Seek supportive company", body: "A teacher, study partner, or encouraging family member can provide perspective and help you remain accountable without pressure." }], takeaway: "Progress belongs to the learner who continues returning with sincerity." },
];

function ArticleModal({ post, onClose }: { post: BlogPost; onClose: () => void }) {
  useEffect(() => { document.body.style.overflow = "hidden"; const onKey = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", onKey); return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", onKey); }; }, [onClose]);
  return <div className="fixed inset-0 z-[9999] overflow-y-auto bg-[#071F1B]/80 p-3 backdrop-blur-lg sm:p-6" role="dialog" aria-modal="true" aria-label={post.title} onClick={onClose}>
    <article className="relative mx-auto my-4 max-w-4xl overflow-hidden rounded-[16px] bg-[#FBF6EF] shadow-2xl sm:my-8" onClick={(event) => event.stopPropagation()}>
      <button type="button" onClick={onClose} aria-label="Close article" className="fixed right-5 top-5 z-[10000] grid size-11 place-items-center rounded-full bg-white text-[#0D463E] shadow-lg sm:absolute"><X className="size-5" /></button>
      <div className="relative aspect-[16/8] w-full"><Image src={post.image} alt={post.title} fill sizes="(min-width: 1024px) 900px, 100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#071F1B]/70 to-transparent" /></div>
      <div className="px-6 py-9 sm:px-12 sm:py-12 min-[900px]:px-16">
        <div className="flex flex-wrap gap-4 font-body text-xs font-semibold text-[#0D463E]/60"><span className="text-[#0D706D]">{post.category}</span><span className="inline-flex items-center gap-1.5"><CalendarDays className="size-3.5" />{post.date}</span><span className="inline-flex items-center gap-1.5"><Clock3 className="size-3.5" />{post.readTime}</span></div>
        <h2 className="mt-5 font-heading text-4xl font-medium leading-[1.08] text-[#0D463E] sm:text-5xl">{post.title}</h2>
        <p className="mt-5 inline-flex items-center gap-2 font-body text-sm text-[#0D463E]/65"><UserRound className="size-4" /> By {post.author}</p>
        <p className="mt-9 font-body text-lg leading-8 text-[#0D463E]/75">{post.introduction}</p>
        <div className="my-10 h-px bg-[#0D463E]/10" />
        <div className="space-y-10">{post.sections.map((section, index) => <section key={section.heading} className="grid gap-4 sm:grid-cols-[48px_1fr]"><span className="grid size-11 place-items-center rounded-full bg-[#0D463E] font-heading text-sm text-[#D0A86C]">0{index + 1}</span><div><h3 className="font-heading text-2xl font-medium text-[#0D463E] sm:text-3xl">{section.heading}</h3><p className="mt-4 font-body text-base leading-8 text-[#0D463E]/68">{section.body}</p></div></section>)}</div>
        <blockquote className="mt-12 rounded-[12px] bg-[#0D463E] p-7 text-white sm:p-9"><Quote className="size-8 text-[#D0A86C]" /><p className="mt-4 font-accent text-xl italic leading-8">{post.takeaway}</p></blockquote>
        <div className="mt-10 flex items-start gap-3 border-t border-[#0D463E]/10 pt-8"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-[#0D706D]" /><p className="font-body text-sm leading-6 text-[#0D463E]/60">Continue learning with a qualified Haramain Quran Institute teacher and turn beneficial knowledge into consistent practice.</p></div>
      </div>
    </article>
  </div>;
}

export default function BlogsLibrary() {
  const [category, setCategory] = useState<(typeof categories)[number]>("All Blogs");
  const [sort, setSort] = useState<SortOption>("Latest");
  const [author, setAuthor] = useState(authors[0]);
  const [activePost, setActivePost] = useState<BlogPost | null>(null);
  const filtered = useMemo(() => [...posts.filter((post) => (category === "All Blogs" || post.category === category) && (author === authors[0] || post.author === author))].sort((a, b) => sort === "Popular" ? b.popularity - a.popularity : sort === "Featured" ? Number(b.featured) - Number(a.featured) || b.id - a.id : b.id - a.id), [category, sort, author]);
  const lead = filtered[0];
  return <section className="w-full bg-white py-24 sm:py-28 min-[1024px]:py-32"><div className="container">
    <div className="mx-auto max-w-4xl text-center"><h2 className="font-heading text-4xl font-medium text-[#0D463E] sm:text-5xl min-[1024px]:text-[58px]">Explore Our <span className="font-accent font-normal italic">Library</span></h2><p className="mx-auto mt-5 max-w-3xl font-body text-base leading-7 text-[#0D463E]/62">Filter by subject or author and open any article for a complete, focused reading experience.</p></div>
    <div className="mt-12 rounded-[18px] border border-[#0D463E]/10 bg-[#FBF6EF] p-4 sm:p-5"><div className="flex items-center gap-2 font-body text-xs font-bold uppercase tracking-[0.15em] text-[#0D463E]/55"><SlidersHorizontal className="size-4" /> Browse articles</div><div className="mt-4 flex flex-wrap gap-2">{categories.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 font-body text-sm font-semibold transition-colors ${category === item ? "bg-[#0D463E] text-white" : "border border-[#0D463E]/12 bg-white text-[#0D463E] hover:bg-[#0D463E]/5"}`}>{item}</button>)}</div><div className="mt-4 grid gap-3 border-t border-[#0D463E]/10 pt-4 sm:grid-cols-2"><label className="flex items-center gap-3 rounded-[8px] bg-white px-4 py-2.5 font-body text-sm text-[#0D463E]"><span className="font-semibold">Sort</span><select value={sort} onChange={(e) => setSort(e.target.value as SortOption)} className="w-full bg-transparent py-1 outline-none"><option>Latest</option><option>Popular</option><option>Featured</option></select></label><label className="flex items-center gap-3 rounded-[8px] bg-white px-4 py-2.5 font-body text-sm text-[#0D463E]"><span className="shrink-0 font-semibold">Author</span><select value={author} onChange={(e) => setAuthor(e.target.value)} className="w-full bg-transparent py-1 outline-none">{authors.map((name) => <option key={name}>{name}</option>)}</select></label></div></div>
    {lead ? <><button type="button" onClick={() => setActivePost(lead)} className="group mt-12 grid w-full overflow-hidden rounded-[16px] border border-[#0D463E]/10 bg-[#FBF6EF] text-left shadow-[0_12px_40px_rgba(13,70,62,0.06)] min-[800px]:grid-cols-[1.2fr_0.8fr]"><div className="relative min-h-[320px]"><Image src={lead.image} alt={lead.title} fill sizes="(min-width: 800px) 60vw, 100vw" className="object-cover transition-transform duration-500 group-hover:scale-[1.03]" /></div><div className="flex flex-col justify-center p-7 sm:p-10"><span className="font-body text-xs font-bold uppercase tracking-[0.14em] text-[#0D706D]">Featured · {lead.category}</span><h3 className="mt-4 font-heading text-3xl font-medium leading-tight text-[#0D463E] sm:text-4xl">{lead.title}</h3><p className="mt-4 font-body text-sm leading-7 text-[#0D463E]/62">{lead.excerpt}</p><div className="mt-6 flex flex-wrap gap-3 font-body text-xs text-[#0D463E]/50"><span>{lead.author}</span><span>·</span><span>{lead.readTime}</span></div><span className="mt-7 inline-flex items-center gap-2 font-body text-sm font-semibold text-[#0D706D]">Read full article <ArrowUpRight className="size-4" /></span></div></button>
    <div className="mt-7 grid gap-6 sm:grid-cols-2 min-[1000px]:grid-cols-3">{filtered.slice(1).map((post) => <button key={post.id} type="button" onClick={() => setActivePost(post)} className="group overflow-hidden rounded-[14px] border border-[#0D463E]/10 bg-white text-left shadow-[0_8px_28px_rgba(13,70,62,0.06)]"><div className="relative aspect-[16/10]"><Image src={post.image} alt={post.title} fill sizes="(min-width: 1000px) 33vw, 50vw" className="object-cover transition-transform duration-500 group-hover:scale-[1.04]" /></div><div className="p-6"><span className="font-body text-[10px] font-bold uppercase tracking-[0.14em] text-[#0D706D]">{post.category}</span><h3 className="mt-3 font-heading text-[23px] font-medium leading-tight text-[#0D463E]">{post.title}</h3><p className="mt-3 font-body text-sm leading-6 text-[#0D463E]/60">{post.excerpt}</p><div className="mt-5 flex items-center justify-between font-body text-xs text-[#0D463E]/50"><span>{post.author}</span><span>{post.readTime}</span></div></div></button>)}</div></> : <div className="mt-12 rounded-[14px] border border-dashed border-[#0D463E]/20 py-16 text-center font-body text-[#0D463E]/60">No blogs match these filters yet.</div>}
  </div>{activePost && <ArticleModal post={activePost} onClose={() => setActivePost(null)} />}</section>;
}
