"use client";

import { useContext, useEffect, useRef, useState } from "react";
import { Bot, Headphones, LockKeyhole, RotateCcw, Sparkles } from "lucide-react";
import { FormPopupContext } from "@/context/FormPopupContext";
import { liveSupportProvider } from "@/lib/live-support";
import ChatInput from "./ChatInput";
import ChatMessage from "./ChatMessage";
import SuggestedPrompt from "./SuggestedPrompt";
import TypingIndicator from "./TypingIndicator";
import type { AssistantMessage, AssistantResponse, ChatSessionContext } from "./types";

const welcome: AssistantMessage = { id: "welcome", role: "assistant", content: "Assalamu alaikum! I’m the Haramain AI Assistant. I can help you explore Quran courses, choose a suitable learning path, or understand classes and scheduling. How may I help you today?" };
const prompts = ["Help me choose a Quran course", "I’m a complete beginner", "Tell me about class schedules", "Do you have female teachers?"];

export default function StartChatAssistant() {
  const { openFormPopup } = useContext(FormPopupContext);
  const [messages, setMessages] = useState<AssistantMessage[]>([welcome]); const [visitorContext, setVisitorContext] = useState<Record<string, string>>({}); const [session, setSession] = useState<ChatSessionContext>({}); const [loading, setLoading] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);
  const sessionIdRef = useRef(""); const inFlightRef = useRef(false); const abortRef = useRef<AbortController | null>(null); const generationRef = useRef(0);
  useEffect(() => { sessionIdRef.current = crypto.randomUUID(); }, []);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" }); }, [messages, loading]);

  const handoff = () => { liveSupportProvider.prepareHandoff(visitorContext); setMessages((current) => [...current, { id: crypto.randomUUID(), role: "assistant", content: "Sure — I’ll prepare a handoff so a member of the Haramain team can help you personally.", handoff: true }]); };
  const send = async (content: string) => {
    if (inFlightRef.current) return;
    inFlightRef.current = true; setLoading(true); const requestId = crypto.randomUUID(); const generation = ++generationRef.current; const controller = new AbortController(); abortRef.current = controller;
    const userMessage: AssistantMessage = { id: requestId, role: "user", content }; const next = [...messages, userMessage]; setMessages(next);
    try { const response = await fetch("/api/haramain-chat", { method: "POST", headers: { "Content-Type": "application/json" }, signal: controller.signal, body: JSON.stringify({ messages: next.slice(-8).map(({ role, content: text }) => ({ role, content: text })), session, sessionId: sessionIdRef.current || (sessionIdRef.current = crypto.randomUUID()), requestId }) }); const data = await response.json() as AssistantResponse & { error?: string }; if (!response.ok) throw new Error(data.error || "The assistant is unavailable."); if (generation !== generationRef.current) return; setSession(data.session); setVisitorContext(Object.fromEntries(Object.entries(data.session).filter(([key, value]) => !["summary", "assessmentStep"].includes(key) && typeof value === "string"))); setMessages((current) => [...current, { id: crypto.randomUUID(), role: "assistant", content: data.message, recommendation: data.recommendation, handoff: data.handoff }]); } catch (error) { if (controller.signal.aborted || generation !== generationRef.current) return; setMessages((current) => [...current, { id: crypto.randomUUID(), role: "assistant", content: error instanceof Error ? error.message : "The assistant is unavailable. Please talk to our team for now.", isError: true }]); } finally { if (generation === generationRef.current) { inFlightRef.current = false; setLoading(false); abortRef.current = null; } }
  };
  const reset = () => { abortRef.current?.abort(); generationRef.current += 1; inFlightRef.current = false; setLoading(false); setMessages([welcome]); setVisitorContext({}); setSession({}); sessionIdRef.current = crypto.randomUUID(); };

  return <section id="assistant" className="bg-[#F2E9DD] py-20 sm:py-24 lg:py-28"><div className="container"><div className="mx-auto max-w-6xl"><div className="mb-10 text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0D706D]">Personal Learning Guidance</p><h2 className="mt-4 font-heading text-4xl font-medium text-[#0D463E] sm:text-5xl">Ask. Discover. Begin.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-[#0D463E]/60">Get grounded answers from Haramain’s website knowledge, one thoughtful question at a time.</p></div>
    <div className="overflow-hidden rounded-[22px] border border-[#0D463E]/10 bg-[#FBF6EF] shadow-[0_32px_90px_rgba(2,28,24,.14)]"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 bg-[#071F1B] px-5 py-4 text-white sm:px-7"><div className="flex items-center gap-3"><div className="relative grid size-11 place-items-center rounded-full bg-[#D0A86C] text-[#071F1B]"><Bot className="size-5" /><span className="absolute bottom-0 right-0 size-3 rounded-full border-2 border-[#071F1B] bg-emerald-400" /></div><div><h3 className="font-heading text-lg">Haramain AI Assistant</h3><p className="mt-0.5 flex items-center gap-1.5 text-[11px] text-white/45"><Sparkles className="size-3 text-[#D0A86C]" /> AI guidance · grounded in Haramain content</p></div></div><div className="flex items-center gap-2"><button type="button" onClick={reset} className="grid size-9 place-items-center rounded-full border border-white/10 text-white/60 hover:bg-white/10" aria-label="Start a new conversation"><RotateCcw className="size-4" /></button><button type="button" onClick={handoff} className="inline-flex h-9 items-center gap-2 rounded-full border border-[#D0A86C]/40 px-4 text-xs font-bold text-[#D0A86C] hover:bg-[#D0A86C]/10"><Headphones className="size-3.5" /> Talk to Our Team</button></div></header>
    <div className="grid lg:grid-cols-[1fr_260px]"><div className="flex min-h-[650px] flex-col"><div className="custom-scrollbar flex-1 space-y-5 overflow-y-auto p-5 sm:p-7 lg:h-[610px] lg:flex-none"><div className="mx-auto max-w-3xl space-y-5">{messages.map((message) => <ChatMessage key={message.id} message={message} visitorContext={visitorContext} onBookTrial={openFormPopup} />)}{loading && <div className="flex gap-3"><div className="grid size-8 place-items-center rounded-full bg-[#0D463E] text-[#D0A86C]"><Bot className="size-4" /></div><div className="rounded-[16px] border border-[#0D463E]/8 bg-white px-4 py-3"><TypingIndicator /></div></div>}<div ref={endRef} /></div></div><div className="border-t border-[#0D463E]/8 bg-white/55 p-4 sm:p-5"><div className="mx-auto max-w-3xl">{messages.length === 1 && <div className="mb-3 flex flex-wrap gap-2">{prompts.map((prompt) => <SuggestedPrompt key={prompt} onClick={() => send(prompt)}>{prompt}</SuggestedPrompt>)}</div>}<ChatInput disabled={loading} onSend={send} /><div className="mt-3 flex flex-wrap items-center justify-between gap-2 px-1 text-[10px] text-[#0D463E]/40"><span className="inline-flex items-center gap-1.5"><LockKeyhole className="size-3" /> AI can make mistakes. Confirm important details with our team.</span><button type="button" onClick={openFormPopup} className="font-bold text-[#0D706D] hover:underline">Book Free Trial</button></div></div></div></div>
    <aside className="border-t border-[#0D463E]/8 bg-[#F7F0E7] p-6 lg:border-l lg:border-t-0"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#9A6C2D]">I can help with</p><ul className="mt-5 space-y-3 text-sm text-[#0D463E]/65">{["Find the right course", "Understand learning levels", "Explore teachers", "Check fee information", "Plan across time zones", "Book a free trial"].map((item) => <li key={item} className="flex items-center gap-2.5"><span className="size-1.5 rounded-full bg-[#D0A86C]" />{item}</li>)}</ul><div className="mt-8 rounded-[12px] bg-[#0D463E] p-5 text-white"><Headphones className="size-5 text-[#D0A86C]" /><h4 className="mt-4 font-heading text-lg">Prefer a person?</h4><p className="mt-2 text-xs leading-5 text-white/55">Prepare a handoff using the information already shared in this conversation.</p><button type="button" onClick={handoff} className="mt-4 text-xs font-bold text-[#D0A86C] hover:underline">Talk to Our Team →</button></div></aside></div></div></div></div></section>;
}
