"use client";

import { Clock3, Download, FileText, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { ResourceItem, ResourcePageConfig } from "./resource-data";

type Filter = "all" | "free" | "paid";

function ResourcePopup({ resource, onClose }: { resource: ResourceItem; onClose: () => void }) {
  useEffect(() => { document.body.style.overflow = "hidden"; const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", close); return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", close); }; }, [onClose]);
  return <div className="fixed inset-0 z-[9999] flex items-center justify-center overflow-y-auto bg-[#071F1B]/80 p-4 backdrop-blur-lg" role="dialog" aria-modal="true" aria-label={`${resource.title} coming soon`} onClick={onClose}><div className="relative my-6 w-full max-w-lg rounded-[var(--radius-lg)] bg-[#FBF6EF] p-6 text-center shadow-2xl sm:p-9" onClick={(event) => event.stopPropagation()}><button type="button" onClick={onClose} aria-label="Close" className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-white text-[#0D463E]"><X className="size-5" /></button><div className="mx-auto grid size-14 place-items-center rounded-full bg-[#0D463E]/8 text-[#0D463E]"><Clock3 className="size-7" /></div><span className="mt-5 inline-flex rounded-full bg-[#0D463E]/8 px-3 py-1 font-body text-xs font-bold uppercase tracking-wide text-[#0D706D]">Free Resource</span><h2 className="mt-5 font-heading text-3xl font-medium text-[#0D463E]">{resource.title}</h2><p className="mt-3 font-body text-sm leading-6 text-[#0D463E]/60">{resource.description}</p><div className="mt-8 rounded-[var(--radius-md)] bg-[#0D463E] p-7 text-white"><h3 className="font-heading text-2xl">Coming Soon</h3><p className="mt-2 font-body text-sm leading-6 text-white/70">This free download is being prepared and will be available soon.</p><button type="button" onClick={onClose} className="mt-5 inline-flex h-11 items-center justify-center rounded-[var(--radius-sm)] bg-[#D0A86C] px-5 font-body text-sm font-bold text-[#071F1B]">Close</button></div>
  </div></div>;
}

export default function ResourcesLibrary({ page }: { page: ResourcePageConfig }) {
  const [filter, setFilter] = useState<Filter>("all"); const [active, setActive] = useState<ResourceItem | null>(null);
  const items = useMemo(() => page.resources.filter((item) => filter === "all" || item.kind === filter), [filter, page.resources]);
  return <section className="w-full bg-white py-24 sm:py-28 min-[1024px]:py-32"><div className="container"><div className="mx-auto max-w-4xl text-center"><h2 className="font-heading text-4xl font-medium text-[#0D463E] sm:text-5xl min-[1024px]:text-[58px]">Books &amp; <span className="font-accent font-normal italic">Downloads</span></h2><p className="mx-auto mt-5 max-w-3xl font-body text-base leading-7 text-[#0D463E]/62">Choose a practical guide to support personal study, family learning, or revision between lessons.</p><div className="mt-8 inline-flex rounded-full bg-[#FBF6EF] p-1.5">{(["all", "free", "paid"] as Filter[]).map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-full px-6 py-2.5 font-body text-sm font-bold capitalize transition-colors ${filter === item ? "bg-[#0D463E] text-white" : "text-[#0D463E] hover:bg-white"}`}>{item === "all" ? "All" : item}</button>)}</div></div><div className="mt-14 grid grid-cols-1 gap-6 sm:grid-cols-2 min-[1100px]:grid-cols-4">{items.map((resource, index) => <article key={resource.filename} className="group flex min-h-[390px] flex-col rounded-[var(--radius-md)] border border-[#0D463E]/10 bg-[#FBF6EF] p-5 shadow-[0_8px_28px_rgba(13,70,62,0.05)]"><div className="relative flex aspect-[4/3] items-center justify-center overflow-hidden rounded-[var(--radius-md)] bg-[#0D463E]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_15%,rgba(208,168,108,0.25),transparent_38%)]" /><FileText className="relative size-14 text-[#D0A86C]" strokeWidth={1.4} /><span className="absolute left-3 top-3 rounded-full bg-white/10 px-2.5 py-1 font-body text-[10px] font-bold uppercase tracking-wider text-white">Coming Soon</span></div><div className="flex flex-1 flex-col pt-6"><div className="flex items-center justify-between gap-3"><span className="font-body text-[10px] font-bold uppercase tracking-[0.14em] text-[#0D706D]">Resource {String(index + 1).padStart(2, "0")}</span><span className="font-heading text-lg font-semibold text-[#0D463E]">Free</span></div><h3 className="mt-3 font-heading text-[22px] font-medium leading-tight text-[#0D463E]">{resource.title}</h3><p className="mt-3 font-body text-sm leading-6 text-[#0D463E]/60">{resource.description}</p><button type="button" onClick={() => setActive(resource)} className="mt-auto flex items-center justify-between border-t border-[#0D463E]/10 pt-5 font-body text-sm font-bold text-[#0D706D]"><span>Download</span><Download className="size-4 transition-transform group-hover:translate-y-0.5" /></button></div></article>)}</div>{items.length === 0 && <div className="mt-14 rounded-[var(--radius-md)] border border-dashed border-[#0D463E]/20 py-16 text-center font-body text-[#0D463E]/60">No paid resources are available right now.</div>}</div>{active && <ResourcePopup resource={active} onClose={() => setActive(null)} />}</section>;
}
