"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, Globe2, Mail, MessageCircle, Phone, Video, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useContext, useEffect, useMemo, useState } from "react";
import { sendTrialBooking } from "@/components/booking/actions/sendTrialBooking";
import { PhoneNumberField, readCompletePhoneNumber, TimeZoneSelect } from "@/components/booking/BookingFields";
import { FormPopupContext } from "@/context/FormPopupContext";

const courses = ["Noorani Qaida", "Quran Reading", "Quran Memorization", "Quran Translation", "Qirat & Tajweed", "Tafsir", "Arabic Language", "Women Guidance", "Nasheed Reciting", "Islamic Studies"];
const slots = Array.from({ length: 26 }, (_, i) => ({ hour: Math.floor((540 + i * 30) / 60), minute: (540 + i * 30) % 60 }));
const toInstant = (date: Date, hour: number, minute: number) => new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(), hour - 5, minute));
const formatted = (date: Date, zone: string) => new Intl.DateTimeFormat("en-US", { timeZone: zone, weekday: "short", month: "long", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit", timeZoneName: "short" }).format(date);
const slotLabel = (date: Date, slot: (typeof slots)[number], zone: string) => new Intl.DateTimeFormat("en-US", { timeZone: zone, hour: "numeric", minute: "2-digit" }).format(toInstant(date, slot.hour, slot.minute));
const inputClass = "mt-2 h-12 w-full rounded-[6px] border border-[#0D463E]/15 bg-white px-4 font-body font-normal text-[#0D463E] outline-none focus:border-[#0D706D]";

export function ContextTrialPopup() {
  const { isFormPopupOpen, closeFormPopup } = useContext(FormPopupContext);
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [day, setDay] = useState<Date | null>(null);
  const [slot, setSlot] = useState<(typeof slots)[number] | null>(null);
  const [zone, setZone] = useState("Asia/Karachi");
  const [busy, setBusy] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { const detected = Intl.DateTimeFormat().resolvedOptions().timeZone; if (detected) setZone(detected); }, []);
  useEffect(() => { if (isFormPopupOpen) { setStep(0); setDay(null); setSlot(null); setSuccess(false); setError(""); } }, [isFormPopupOpen]);
  const days = useMemo(() => Array.from({ length: 21 }, (_, i) => { const d = new Date(); d.setHours(12, 0, 0, 0); d.setDate(d.getDate() + i + 1); return d; }), []);
  const instant = day && slot ? toInstant(day, slot.hour, slot.minute) : null;
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!instant || busy) return; setBusy(true); setError(""); const data = new FormData(event.currentTarget);
    const result = await sendTrialBooking({ organizerName: String(data.get("organizerName") || ""), studentName: String(data.get("studentName") || ""), email: String(data.get("email") || ""), phone: readCompletePhoneNumber(data), contactMethod: String(data.get("contactMethod") || "Email"), course: String(data.get("course") || ""), timezone: zone, studentTime: formatted(instant, zone), pakistanTime: formatted(instant, "Asia/Karachi"), utcTime: instant.toISOString(), notes: String(data.get("notes") || ""), sourcePage: window.location.pathname });
    setBusy(false); if (!result.success) { setError(result.error || "Unable to complete booking."); return; } setSuccess(true); window.setTimeout(() => { closeFormPopup(); router.push("/sessions"); }, 2600);
  };
  const stepNames = ["Select date", "Select time", "Your details"];
  return <Dialog.Root open={isFormPopupOpen} onOpenChange={(open) => !open && closeFormPopup()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[80] bg-[#021C18]/80 backdrop-blur-xl"/><Dialog.Content className="fixed left-1/2 top-1/2 z-[90] max-h-[calc(100vh-24px)] w-[calc(100%-24px)] max-w-[1180px] -translate-x-1/2 -translate-y-1/2 overflow-hidden rounded-[18px] border border-white/10 bg-[#FBF6EF] text-[#0D463E] shadow-2xl"><Dialog.Title className="sr-only">Book a free trial class</Dialog.Title><Dialog.Description className="sr-only">Choose a date, time, and enter learner details.</Dialog.Description><Dialog.Close className="absolute right-4 top-4 z-20 grid size-10 place-items-center rounded-full bg-white shadow-md" aria-label="Close booking"><X className="size-5"/></Dialog.Close>
    {success ? <div className="flex min-h-[620px] flex-col items-center justify-center px-6 text-center"><div className="grid size-24 place-items-center rounded-full bg-[#0D463E]"><Check className="size-12 text-[#D0A86C]"/></div><p className="mt-8 font-body text-xs font-bold uppercase tracking-[0.22em] text-[#0D706D]">Booking Confirmed</p><h2 className="mt-4 font-heading text-6xl font-medium">Thank You!</h2><p className="mt-5 max-w-2xl font-body text-base leading-7 text-[#0D463E]/65">Your trial is booked and confirmation emails have been sent. We’re taking you to Our Sessions.</p><div className="mt-8 h-1.5 w-56 overflow-hidden rounded-full bg-[#0D463E]/10"><div className="h-full w-full origin-left animate-[booking-progress_2.6s_linear_forwards] bg-[#D0A86C]"/></div></div> :
    <div className="grid min-h-[650px] max-h-[calc(100vh-24px)] min-[900px]:grid-cols-[320px_1fr]"><aside className="bg-[#071F1B] p-7 text-white sm:p-9"><div className="grid size-12 place-items-center rounded-full bg-[#D0A86C] font-heading text-xl font-bold text-[#071F1B]">H</div><p className="mt-7 font-body text-xs font-bold uppercase tracking-[0.18em] text-[#D0A86C]">Haramain Quran Institute</p><h2 className="mt-3 font-heading text-3xl">Free Trial Class</h2><p className="mt-4 font-body text-sm leading-6 text-white/60">Meet your teacher, ask questions, and experience a personal Quran lesson—without pressure.</p><div className="mt-8 space-y-4 font-body text-sm text-white/75"><p className="flex gap-3"><Clock3 className="size-4 text-[#D0A86C]"/>30 minutes</p><p className="flex gap-3"><Video className="size-4 text-[#D0A86C]"/>Google Meet</p><p className="flex gap-3"><Globe2 className="size-4 text-[#D0A86C]"/>Your local time zone</p></div>{instant && <div className="mt-8 rounded-[10px] border border-white/10 bg-white/[.05] p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[#D0A86C]">Your time</p><p className="mt-2 text-sm leading-6">{formatted(instant, zone)}</p><p className="mt-3 border-t border-white/10 pt-3 text-xs leading-5 text-white/50">Pakistan: {formatted(instant, "Asia/Karachi")}</p></div>}</aside>
    <div className="flex max-h-[calc(100vh-24px)] flex-col overflow-hidden"><div className="border-b border-[#0D463E]/10 px-6 pb-4 pt-7 sm:px-9"><div className="flex items-center gap-2">{stepNames.map((name, i) => <div key={name} className="flex flex-1 items-center gap-2"><span className={`grid size-7 shrink-0 place-items-center rounded-full text-xs font-bold ${i <= step ? "bg-[#0D463E] text-white" : "bg-[#0D463E]/8 text-[#0D463E]/45"}`}>{i < step ? <Check className="size-3.5"/> : i + 1}</span><span className="hidden text-xs font-semibold sm:block">{name}</span>{i < 2 && <span className="ml-auto h-px flex-1 bg-[#0D463E]/10"/>}</div>)}</div></div>
    <div className="flex-1 overflow-y-auto px-6 py-7 sm:px-9 sm:py-9">{step === 0 && <div><h3 className="font-heading text-4xl">Select a date</h3><p className="mt-2 text-sm text-[#0D463E]/55">Choose a convenient day for your 30-minute trial.</p><TimeZoneSelect value={zone} onChange={setZone} /><div className="mt-7 grid grid-cols-3 gap-3 sm:grid-cols-5 lg:grid-cols-7">{days.map((d) => { const active = day?.toDateString() === d.toDateString(); return <button key={d.toISOString()} type="button" onClick={() => setDay(d)} className={`rounded-[10px] border p-3 ${active ? "border-[#0D463E] bg-[#0D463E] text-white" : "border-[#0D463E]/10 bg-white"}`}><span className={`block text-[10px] font-bold uppercase ${active ? "text-[#D0A86C]" : "text-[#0D463E]/45"}`}>{d.toLocaleDateString("en-US",{weekday:"short"})}</span><span className="mt-1 block font-heading text-2xl">{d.getDate()}</span><span className="text-[10px]">{d.toLocaleDateString("en-US",{month:"short"})}</span></button>})}</div></div>}
    {step === 1 && day && <div><h3 className="font-heading text-4xl">Select a time</h3><p className="mt-2 text-sm text-[#0D463E]/55">Shown in {zone.replaceAll("_", " ")}.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{slots.map((s) => <button key={`${s.hour}-${s.minute}`} type="button" onClick={() => setSlot(s)} className={`rounded-[8px] border px-4 py-3.5 text-sm font-bold ${slot?.hour === s.hour && slot.minute === s.minute ? "border-[#0D463E] bg-[#0D463E] text-white" : "border-[#0D463E]/12 bg-white"}`}>{slotLabel(day,s,zone)}</button>)}</div></div>}
    {step === 2 && instant && <form id="trial-booking-form" onSubmit={submit}><h3 className="font-heading text-4xl">Your details</h3><p className="mt-2 text-sm text-[#0D463E]/55">Help us prepare the right trial experience.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Parent / organizer name<input name="organizerName" required className={inputClass}/></label><label className="text-sm font-semibold">Student name<input name="studentName" required className={inputClass}/></label><label className="text-sm font-semibold">Email address<input name="email" type="email" required className={inputClass}/></label><label className="text-sm font-semibold">Phone / WhatsApp<PhoneNumberField /></label><label className="text-sm font-semibold sm:col-span-2">Course<select name="course" required defaultValue="" className={inputClass}><option value="" disabled>Select a course</option>{courses.map((course) => <option key={course}>{course}</option>)}</select></label></div><fieldset className="mt-5"><legend className="text-sm font-semibold">Preferred contact method</legend><div className="mt-3 grid grid-cols-3 gap-2">{[["Email",Mail],["WhatsApp",MessageCircle],["Phone",Phone]].map(([value,Icon],i) => { const ContactIcon = Icon as typeof Mail; return <label key={value as string} className="cursor-pointer"><input type="radio" name="contactMethod" value={value as string} defaultChecked={i===0} className="peer sr-only"/><span className="flex items-center justify-center gap-2 rounded-[7px] border bg-white px-3 py-3 text-xs font-bold peer-checked:bg-[#0D463E] peer-checked:text-white"><ContactIcon className="size-4"/>{value as string}</span></label>})}</div></fieldset><label className="mt-5 block text-sm font-semibold">Additional notes<textarea name="notes" rows={3} className="mt-2 w-full rounded-[6px] border border-[#0D463E]/15 bg-white px-4 py-3 font-normal outline-none" placeholder="Current level, preferred teacher, or learning needs..."/></label>{error && <p role="alert" className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}</form>}</div>
    <div className="flex justify-between border-t border-[#0D463E]/10 bg-white px-6 py-4 sm:px-9"><button type="button" onClick={() => setStep(Math.max(0,step-1))} disabled={step===0} className="inline-flex items-center gap-2 text-sm font-bold disabled:invisible"><ArrowLeft className="size-4"/>Back</button>{step<2 ? <button type="button" onClick={() => setStep(step+1)} disabled={(step===0&&!day)||(step===1&&!slot)} className="inline-flex h-11 items-center gap-2 rounded-[6px] bg-[#0D463E] px-6 text-sm font-bold text-white disabled:opacity-35">Next<ArrowRight className="size-4"/></button> : <button form="trial-booking-form" type="submit" disabled={busy} className="inline-flex h-11 items-center gap-2 rounded-[6px] bg-[#0D463E] px-6 text-sm font-bold text-white disabled:opacity-50">{busy?"Confirming...":"Confirm Booking"}<CheckCircle2 className="size-4"/></button>}</div></div></div>}
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
